In [1]:
import pandas as pd
from keras.models import Sequential, model_from_json
from keras.layers import Dense
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder

Using TensorFlow backend.

In [2]:
df = pd.read_csv("raw_input.csv")
cols = [0,1]
df2 = df.drop(df.columns[cols],axis=1)
df2 = df2.fillna(100)
df2

,Home,ML,Spread,Over,season_wins,net_points,avg_for_fg,avg_for_fgp,avg_opp_fgp,avg_for_3p,...,avg_opp_3pp,avg_for_ft,avg_for_ftp,avg_opp_fta,avg_for_rb,avg_opp_rb,avg_for_blk,avg_opp_blk,avg_for_to,avg_opp_to
0,1,245,6.1,231.8,34,-80.3,42.5,0.468,0.450,10.9,...,0.365,16.6,0.763,25.0,46.5,44.9,5.5,5.3,15.2,14.9
1,0,-295,-6.1,231.8,35,-81.4,42.2,0.463,0.456,12.9,...,0.383,17.7,0.804,24.7,45.3,46.9,6.1,4.9,12.8,12.7
2,1,-154,-3.2,218.7,46,153.3,42.0,0.473,0.463,11.0,...,0.358,16.2,0.777,22.5,44.2,42.7,4.6,4.4,13.8,14.3
3,0,134,3.2,218.7,44,180.0,40.1,0.471,0.457,13.4,...,0.353,17.8,0.779,21.5,44.9,42.7,4.1,4.6,15.1,12.4
4,1,369,9.6,223.7,35,-36.0,40.4,0.448,0.446,13.1,...,0.350,17.9,0.745,22.6,48.0,46.0,4.5,5.3,15.3,13.0
5,0,-469,-9.6,223.7,53,453.6,40.2,0.458,0.428,13.8,...,0.337,18.5,0.796,23.2,45.4,46.0,5.0,5.5,14.8,16.8
6,1,-217,-5.5,220.0,48,460.8,41.3,0.461,0.441,12.6,...,0.340,18.6,0.801,24.5,46.1,44.3,5.6,5.5,13.8,15.2
7,0,184,5.5,220.0,43,167.9,41.1,0.468,0.463,11.6,...,0.353,16.9,0.755,24.5,45.5,41.8,5.3,4.0,14.2,14.0
8,1,198,5.8,230.7,43,367.5,41.7,0.461,0.458,15.1,...,0.351,18.6,0.779,21.0,46.9,45.4,4.8,4.1,12.7,11.9
9,0,-238,-5.8,230.7,49,460.8,41.6,0.466,0.438,12.4,...,0.345,20.8,0.791,24.5,47.7,45.3,4.7,4.7,14.6,14.3
10,1,-748,-11.2,224.5,56,737.3,43.3,0.476,0.414,13.8,...,0.355,18.3,0.742,21.2,51.7,45.8,5.9,4.5,15.1,14.0
11,0,544,11.2,224.5,33,-73.0,39.3,0.444,0.465,11.1,...,0.364,17.6,0.774,19.8,44.5,44.8,5.4,4.6,12.8,14.7
12,1,156,3.8,217.2,45,138.7,42.1,0.476,0.446,10.2,...,0.341,15.0,0.787,21.6,42.8,45.3,5.2,4.6,13.2,14.6
13,0,-178,-3.8,217.2,44,211.7,39.5,0.468,0.448,13.4,...,0.347,19.7,0.783,23.6,44.4,42.5,4.5,4.1,14.9,14.5
14,1,100,1.5,227.0,44,216.0,40.8,0.451,0.462,15.6,...,0.349,20.6,0.791,23.7,44.3,47.9,5.2,4.9,14.7,15.9
15,0,-120,-1.5,227.0,44,144.0,40.0,0.468,0.455,10.7,...,0.340,19.8,0.796,19.6,42.9,44.8,4.9,4.0,13.7,14.3

In [3]:
# def load_model():
#     # loading model
#     model = model_from_json(open('ML_model_architecture.json').read())
#     model.load_weights('ML_model_weights.h5')
#     model.compile(loss='categorical_crossentropy', optimizer='adam')
#     return model

In [4]:
from joblib import dump, load
rf = load('spread_model.joblib')
clf = load('s_payout_model.joblib')

In [5]:
predictions_s = rf.predict(df2).tolist()
predictions_po = clf.predict(df2).tolist()
df.drop(df.columns[5:],axis=1,inplace=True)
df['s_outcome'] = predictions_s
df['exp_payout'] = predictions_po
cols = [0,3]
df.drop(df.columns[cols],axis=1,inplace=True)
df

   Team  Home  Spread  s_outcome  exp_payout
0   MEM     1     6.1          1   16.062392
1   POR     0    -6.1          0   -6.030412
2   DEN     1    -3.2          1   -2.107458
3   UTA     0     3.2          1    8.977892
4   BRK     1     9.6          1   15.382925
5   TOR     0    -9.6          1    5.850517
6   BOS     1    -5.5          1    2.728047
7   PHI     0     5.5          1   13.235193
8   DAL     1     5.8          1    8.599649
9   LAC     0    -5.8          0   -0.056510
10  MIL     1   -11.2          1   -5.153761
11  ORL     0    11.2          1   19.899068
12  IND     1     3.8          1   14.095113
13  MIA     0    -3.8          1   12.471413
14  HOU     1     1.5          1    0.431987
15  OKC     0    -1.5          1    2.225119

In [6]:
# load
# model = load_model()

# # predictions
# predictions = model.predict_classes(df2, verbose=2)
# print(predictions)

In [7]:
# p = predictions.tolist()
# df['ml_outcome'] = p
# cols = [0,2,5,6,7,8]
# df.drop(df.columns[cols],axis=1,inplace=True)
# df

In [8]:
df.to_csv('s_predictions.csv')