In [1]:
import pandas as pd
from keras.models import Sequential, model_from_json
from keras.layers import Dense
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder

Using TensorFlow backend.

In [2]:
df = pd.read_csv("raw_input.csv")
cols = [0,1]
df2 = df.drop(df.columns[cols],axis=1)
df2 = df2.fillna(100)
df2

,Home,ML,Spread,Over,season_wins,net_points,avg_for_fg,avg_for_fgp,avg_opp_fgp,avg_for_3p,...,avg_opp_3pp,avg_for_ft,avg_for_ftp,avg_opp_fta,avg_for_rb,avg_opp_rb,avg_for_blk,avg_opp_blk,avg_for_to,avg_opp_to
0,1,183,5.0,224.5,43,172.5,40.1,0.471,0.455,10.5,...,0.338,19.8,0.797,19.1,42.7,44.5,4.9,4.0,13.6,14.1
1,0,-216,-5.0,224.5,31,-49.0,40.9,0.465,0.473,11.3,...,0.363,19.8,0.832,24.8,43.3,43.5,3.9,5.6,14.9,15.7
2,1,250,7.5,223.9,42,396.0,41.6,0.460,0.456,15.2,...,0.348,18.5,0.777,20.9,47.3,45.4,4.9,4.1,12.8,12.1
3,0,-300,-7.5,223.9,43,182.0,40.0,0.471,0.455,13.2,...,0.351,17.9,0.778,21.3,45.0,42.8,4.0,4.5,15.3,12.5
4,1,-242,-6.0,227.8,55,742.0,43.5,0.478,0.413,13.7,...,0.356,18.2,0.744,21.0,51.9,45.6,6.0,4.5,15.0,14.0
5,0,202,6.0,227.8,50,427.8,40.1,0.458,0.428,13.7,...,0.335,18.5,0.802,22.9,45.1,46.1,4.9,5.3,14.8,16.7
6,1,145,3.6,220.3,43,140.0,42.3,0.478,0.449,10.1,...,0.344,15.1,0.790,21.5,42.5,44.9,5.2,4.5,13.1,14.4
7,0,-165,-3.6,220.3,43,217.0,39.5,0.469,0.448,13.5,...,0.347,19.9,0.784,23.7,44.2,42.3,4.5,4.2,14.9,14.4
8,1,176,5.0,221.0,46,182.0,42.1,0.472,0.460,10.8,...,0.354,16.2,0.776,22.5,44.3,42.7,4.6,4.5,13.8,14.4
9,0,-207,-5.0,221.0,51,427.8,42.2,0.478,0.445,10.9,...,0.344,17.8,0.730,23.1,46.0,42.3,6.7,3.8,15.2,15.7

In [3]:
# def load_model():
#     # loading model
#     model = model_from_json(open('ML_model_architecture.json').read())
#     model.load_weights('ML_model_weights.h5')
#     model.compile(loss='categorical_crossentropy', optimizer='adam')
#     return model

In [4]:
from joblib import dump, load
rf = load('spread_model.joblib')

In [5]:
predictions = rf.predict(df2).tolist()
df.drop(df.columns[5:],axis=1,inplace=True)
df['s_outcome'] = predictions
cols = [0,3]
df.drop(df.columns[cols],axis=1,inplace=True)
df

  Team  Home  Spread  s_outcome
0  OKC     1     5.0          1
1  PHO     0    -5.0          0
2  DAL     1     7.5          1
3  UTA     0    -7.5          0
4  MIL     1    -6.0          1
5  TOR     0     6.0          1
6  IND     1     3.6          1
7  MIA     0    -3.6          1
8  DEN     1     5.0          1
9  LAL     0    -5.0          1

In [6]:
# load
# model = load_model()

# # predictions
# predictions = model.predict_classes(df2, verbose=2)
# print(predictions)

In [7]:
# p = predictions.tolist()
# df['ml_outcome'] = p
# cols = [0,2,5,6,7,8]
# df.drop(df.columns[cols],axis=1,inplace=True)
# df

In [8]:
df.to_csv('s_predictions.csv')